---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: platform-automation
  type: pivnet
  source:
    product_slug: platform-automation
    api_token: ((pivnet-refresh-token))
- name: env
  type: git
  source:
    uri: ((pipeline-repo))
    private_key: ((plat-auto-pipes-deploy-key.private_key))
- name: installation
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    secret_access_key: ((s3_secret_access_key))
    region_name: us-west-2
    bucket: ((platform-automation-bucket))
    regexp: foundation/installation-(.*).zip

jobs:
- name: export-installation
  serial: true
  plan:
    - get: platform-automation-image
      tags:
      - vsphere
      resource: platform-automation
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      tags:
      - vsphere
      resource: platform-automation
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: env
      tags:
      - vsphere
    - task: credhub-interpolate
      tags:
      - vsphere
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        PREFIX: ((credhub-prefix))
        INTERPOLATION_PATH: platform-automation/vsphere/env/env.yml
      input_mapping:
        files: env
      output_mapping:
        interpolated-files: interpolated-env
    - task: export-installation
      tags:
      - vsphere
      image: platform-automation-image
      file: platform-automation-tasks/tasks/export-installation.yml
      params:
        ENV_FILE: platform-automation/vsphere/env/env.yml
      input_mapping:
        env: interpolated-env
    - put: installation
      tags:
      - vsphere
      params:
        file: installation/installation-*.zip

- name: upgrade-ops-manager
  serial: true
  plan:
  - get: platform-automation-image
    resource: platform-automation
    params:
      globs: ["*image*.tgz"]
      unpack: true
  - get: platform-automation-tasks
    resource: platform-automation
    params:
      globs: ["*tasks*.zip"]
      unpack: true
  - get: env
  - get: installation
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      PREFIX: ((credhub-prefix))
      INTERPOLATION_PATH: |
        platform-automation/vsphere/env/env.yml
        foundation/download-opsman.yml
        foundation/opsman.yml
      # Remove foundation/opsman.yml if you don't have secrets in this file.
    input_mapping:
      files: env
  - task: download-opsman-image
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: download-opsman.yml
  - task: upgrade-ops-manager
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upgrade-ops-manager.yml
    input_mapping:
      config: env
      image: downloaded-product
      secrets: interpolated-files
      state: env
    params:
      ENV_FILE: platform-automation/vsphere/env/env.yml
      OPSMAN_CONFIG_FILE: foundation/opsman.yml
      STATE_FILE: foundation/state.yml
